### ISSUE TITLE
Adding to a squarespace site, X and Y coordinates not being picked up correct or offset or something

### ISSUE THREAD

**Issue by MajorTennis** [tholman/cursor-effects#12]
https://codepen.io/tholman/pen/rxJpdQ
Trying to add this to a friends website for them but having a bit of trouble with alignment

document.body.appendChild(this.element); 

Throws all the emojis to the bottom of the page and none show over the content only below, I think this is because of a clear fix.

If Insert it in a div above the clearfix , the x and y coordinates are all slightly off. 

Any help would be appreciated

**Comment by tholman** [comment]
Out of curiosity, does this one work https://codepen.io/tholman/pen/babd84d93bf7a263cb4f768119a49eee ... I know its not emoji's right now, but I was planning to re-release these in a more efficiently coded way, adding the emoji's wouldn't be too tricky I don't think

**Comment by MajorTennis** [comment]
It has similar issues http://saphirerose.com/

**Comment by MajorTennis** [comment]
I'm sure its just something with the squarespace design over riding something

**Comment by tholman** [comment]
Ahh, it will be something to do with how I'm getting the cursor position by the looks of it

```   
const boundingRect = e.target.getBoundingClientRect()
cursor.x = e.clientX - boundingRect.left;
cursor.y = e.clientY - boundingRect.top;
```

I'd guess changing that above to just this might amend it?

```   
cursor.x = e.clientX;
cursor.y = e.clientY;
```

I really been looking to revive this project and fix them all up, but realistically probably in a couple of weeks.

**Comment by MajorTennis** [comment]
Thanks man that works without issue

**Comment by tholman** [comment]
🙏 Will close this issue when I patch all that stuff out. Thanks for testing/getting back 🙏

**Comment by Va1a** [comment]
Hello, I have a similar issue with the Ghost Cursor. The particles seem to appear at an offset making them a considerable amount lower than the normal cursor. site: https://irony.club

**Comment by MajorTennis** [comment]
@va1a looks like the same issue I was having, a combination of the above fixed it for me .
https://codepen.io/tholman/pen/babd84d93bf7a263cb4f768119a49eee  does this one work for you

**Comment by Va1a** [comment]
@MajorTennis It works better, but at random points on the page the effect is offset still (noticeably, when hovering over hyperlinks) Vid: https://i.gyazo.com/2506c12aab58ddb6f87e35ee4533214d.mp4

**Comment by Va1a** [comment]
@tholman any tips on this?

**Comment by tholman** [comment]
Will try to modernize it tonight :)

**Comment by tholman** [comment]
Yeah, a lot to do here but a little slow burn as I fix up a whole site for these, a new template for new effects, site to demo etc... all to be done in chill afternoons when lookin for some code to chew on.

That said, hows this JS for your site - https://codepen.io/tholman/pen/babd84d93bf7a263cb4f768119a49eee

**Comment by Va1a** [comment]
Thank you so much @tholman , works great! For those also trying to use the solution, make sure to add: `html {
   margin: 0px;
   height: 100%;
   width: 100%;
}

body {
   margin: 0px;
   min-height: 100%;
   width: 100%;
}` to your css, so that the cursor affect applies everywhere on the webpage (in case your body does not take up the entire screen)

**Comment by tholman** [comment]
Fixed up in the rewrite I believe!
