### ISSUE TITLE
FIrefox 82.0a1. Cursor Effects using emojis are broken because weird BoundingBoxes

### ISSUE THREAD

**Issue by HartleyAHartley** [tholman/cursor-effects#16]
For snowFlake, emoji, and springyEmoji the drawImage call fails.
This is because the TextMetrics returned from measureText have bounding box values that add to zero.
```
TextMetrics
    actualBoundingBoxAscent: -3.843
    actualBoundingBoxDescent: 3.843
    actualBoundingBoxLeft: 10.5
    actualBoundingBoxRight: -10.5
    width: 21
```

```
      let measurements = context.measureText(emoji);
      let bgCanvas = document.createElement("canvas");
      let bgContext = bgCanvas.getContext("2d");

      bgCanvas.width = measurements.width;
      bgCanvas.height =
        measurements.actualBoundingBoxAscent +
        measurements.actualBoundingBoxDescent;

      bgContext.textAlign = "center";
      bgContext.font = "21px serif";
      bgContext.textBaseline = "middle";
      bgContext.fillText(
        emoji,
        bgCanvas.width / 2,
        measurements.actualBoundingBoxAscent
      );
```

The easier fix I found is just using the height for the width, but no idea how other browser would take that.
The ghostCursor is also broke for me, but I wasn't able to find out why.

**Comment by tholman** [comment]
Ooh interesting. I'm thinking these are probably regressions on the firefox alpha so wouldn't mind waiting to see as it moves on. 

Have fixed the ghost cursor though, was a strange base64 format that firefox wasn't able to handle 🤷

**Comment by tholman** [comment]
I've ended up using 2x Ascent here... which seems to have worked out on my tests

**Comment by yaomtc** [comment]
Firefox 104 does not render the emoji properly. It is cut off and only a bottom portion is shown.
