### ISSUE TITLE
here is a bunch of old examples

### ISSUE THREAD

**Issue by sknebel** [tholman/cursor-effects#2]
The page seems to have been around for ages, there are some really crazy ones:

http://rainbow.arch.scriptmania.com/scripts/index.html

I remember http://rainbow.arch.scriptmania.com/scripts/elasticballs.html from waaaay back.
No info about licenses though, so I don't want to directly copy them here.

**Comment by anko** [comment]
Oh the memories!

I also remember [hypergurl.com](http://www.hypergurl.com/easyhtml.html)—their demos don't seem to be embedded in the pages that describe them anymore though.

**Comment by ahmetalpbalkan** [comment]
Comet trail FTW! http://rainbow.arch.scriptmania.com/scripts/comet_cursor.html though I've seen better ones back in the day.

**Comment by tholman** [comment]
Got the elastic balls!, sadly the rest of these are lost to the ages. If anyone can find the scripts, I will gladly convert them to a more modern workable version 👯

**Comment by N6UDP** [comment]
@tholman 
I blame HN for me necroing this but it would appear all of the effects live on ..sorta 
https://web.archive.org/web/20180814202445/http://rainbow.arch.scriptmania.com/scripts/index.html
https://web.archive.org/web/20180905222147/http://www.rainbow.arch.scriptmania.com/scripts/elastic_pumpkin.html 
works just fine work example.
https://web.archive.org/web/20180905060304/http://www.rainbow.arch.scriptmania.com/scripts/bats_halloween.html
doesn't seem to work but the script/code is there.
