### ISSUE TITLE
Toggle Cursor effects

### ISSUE THREAD

**Issue by pard68** [tholman/cursor-effects#33]
I'm wondering if there is a way to toggle the cursor on and off. I like the clock cursor, brings some retro early 00s flair, but it also interfers with reading websites. I have a event listening for `mousemove` and if the `main` tag is in the `:hover` query selector results I would like to turn off the cursor.

**Comment by pard68** [comment]
This might also be needed for things that don't reload the dom when a new page loads. With NextJS I am seeing a duplicate cursor being created with every click because NextJS only updates elements that change in the DOM and doesn't repaint the whole dome, thus it doesn't clear objects/values/state/etc, like the cursor.

**Comment by tholman** [comment]
Definitely seems like something that should be easy to add!

**Comment by tholman** [comment]
Can now call `.destroy()` on the effects
