### ISSUE TITLE
how can I add this to my react project?

### ISSUE THREAD

**Issue by psycho-baller** [tholman/cursor-effects#39]
I tried installing it with NPM but it didn't work

**Comment by tholman** [comment]
Hey mate, going to need a little more info, was there any errors? or problems with running the code specifically?

**Comment by psycho-baller** [comment]
Wait so it's supposed to work normally with react?

**Comment by tholman** [comment]
Sorry, it can definitely work within react, though it'll need to be assigned an element via a ref? Just adding the module won't do anything , really need details, was there any errors or problems running the functions?
