### ISSUE TITLE
"Uncaught SyntaxError: ambiguous indirect export: default" when importing into firefox (via replit)

### ISSUE THREAD

**Issue by Afterlifepro** [tholman/cursor-effects#42]

**Comment by tholman** [comment]
Could you send over your replit, trying to debug this one

**Comment by Afterlifepro** [comment]
https://debug-tholman-cursor-effects.will30.repl.co/  hope this helps
its just a default repl tho lol

**Comment by tholman** [comment]
For esm, you'll need to import the individual cursor you're using, i can see my readme is messed up here, so will leave this open and fix the readme when i get a minute!

https://codepen.io/tholman/pen/GRGyOpK/e547170bbe222e706f430f47ef69882d

**Comment by tholman** [comment]
Docs updated!
