### ISSUE TITLE
this is undefined error in last releases

### ISSUE THREAD

**Issue by revoltek-daniel** [tholman/cursor-effects#43]
Hello,

since 1.0.5 i get the error message "this is undefined" it looks like it is caused by this commit 
https://github.com/tholman/cursor-effects/commit/c4b4aef2cd371d2c32b23d903ccb65c0be5a4a64

**Comment by tholman** [comment]
Could you send over your code in a little demo plz, looking to debug.

**Comment by revoltek-daniel** [comment]
`import {fairyDustCursor} from 'cursor-effects'

fairyDustCursor({colors: ["#ff0000", "#00ff00", "#0000ff"]});`

compile this with webpack and you get the undefined error on "this.destroy"


`<html>
<head>
    <title>test</title>
    <script src="https://unpkg.com/cursor-effects@latest/dist/browser.js"></script>
<script>
    new cursoreffects.fairyDustCursor({colors: ["#ff0000", "#00ff00", "#0000ff"]});
</script>
</head>
<body></body>
</html>`

leads to another "Uncaught TypeError: n is null" errorin [browser.js:1:9861](https://unpkg.com/cursor-effects@latest/dist/browser.js)

**Comment by tholman** [comment]
Ahh, it looks like in test 2 the function needs to be in a window.onload (or in the body) to run after the body exists, I should be able to make a fix for that. 

As for 1, im not quite sure why it won't allow an assignment to `this` in the compiled version but should be able to figure it out this week/weekend

**Comment by tholman** [comment]
Feels like the main bug is covered. I will add some documentation to ensure that the function is called when a body exists if its working correctly for you
