### ISSUE TITLE
Index html

### ISSUE THREAD

**Issue by klj2000** [tholman/cursor-effects#44]
Not sure why but there is no reference to the .js files to the scr folder in the index.html file  so none of these work when you load the page. So not sure if their was a reason for this or not but thought I would bring it up in case.

**Comment by tholman** [comment]
Ahh, you need to npm install and build, I should add these to the readme

**Comment by evavesely** [comment]
has this been resolved? tyy

**Comment by tholman** [comment]
Instructions added here https://github.com/tholman/cursor-effects#how-to-set-up-locallydevelop
