### ISSUE TITLE
change color without destroying first?

### ISSUE THREAD

**Issue by meewgumi** [tholman/cursor-effects#57]
is there an option for `followingDotCursor({ color: ["#323232a6"] })` that allows you to set a new hex code without destroying & creating a new cursor first?

**Comment by tholman** [comment]
There is not. Feel free to create one & add to the documentation, will happily merge it in!

Would call the function `updateProps` or something along that lines, you can expose it the same way destroy is exposed

**Comment by 5093912** [comment]
cool
