### ISSUE TITLE
the library doesnt work as espected

### ISSUE THREAD

**Issue by Trongar** [tholman/cursor-effects#59]
I'm trying to add the effect to my svelt project, but the console say's this
```This browser has prefers reduced motion turned on, so the cursor did not init```
and here is how im trying to make it
```js
import { onMount } from 'svelte';
import { rainbowCursor } from "cursor-effects";
let canvas3d ;
onMount(()=>{
  new rainbowCursor({
    length: 3,
    colors: ["red", "blue"],
    size: 4,
  });
})
```

**Comment by tholman** [comment]
Do you have prefers reduced motion turned on?

**Comment by Trongar** [comment]
i don't know, i have test it in opera, chrome, edge and firefox and i've got the same

**Comment by Trongar** [comment]
event the [page](https://tholman.com/cursor-effects/) works whell

**Comment by tholman** [comment]
Ya, its a system setting. If you turn it off you will see the effects.

https://stackoverflow.com/questions/59708960/how-do-i-change-the-prefers-reduced-motion-setting-in-browsers

**Comment by Trongar** [comment]
thanks, even i've solve it by deleting the condition, I don't know what kind of bug it will trace, but a least it works for me, thank you
