### ISSUE TITLE
Appearing under body

### ISSUE THREAD

**Issue by Ashlyxz** [tholman/cursor-effects#64]
Im a bit of a newbie at website design, but I have a domain and hosting plan using hostinger, but when I try to use this via inserting it into the head, it shows beneath the body. Any ideas?
![image](https://github.com/tholman/cursor-effects/assets/92411169/1080aa26-d423-43fd-a964-8c3ca22c87f0)
![image](https://github.com/tholman/cursor-effects/assets/92411169/b70696ef-7ac1-46da-b70e-468533c28f6d)

**Comment by tholman** [comment]
A little tricky to debug here, could you link to your site?

**Comment by tholman** [comment]
The most likely scenario is that there are some css resets that are applying to the canvas

**Comment by Ashlyxz** [comment]
Sorry for the delay, have a really killer tension headache that I'm seeing a doctor about tomorrow, ended up fixing it, and if you wanna check out the website that it's being used on it's my personal landing page [here.](https://honoralogic.com)

**Comment by tholman** [comment]
Oh nice, appreciate you closing it out. Take care of urself!!
