### ISSUE TITLE
Canvas has a height of 100vh and glitches after

### ISSUE THREAD

**Issue by marianssen** [tholman/cursor-effects#72]
Hi,

I'm not sure if I'm doing something wrong. I'm using characterCursor and the canvas size is always 100vh. After scrolling down, the effect starts glitching (letters do not dissapear). I've trie using fixed position on the canvas, but this did not solve the issue. Is there any way, how to solve this?

Regards

**Comment by tholman** [comment]
Do you have a demo page, or codepen that I could see?

**Comment by marianssen** [comment]
> Do you have a demo page, or codepen that I could see?

Yes, here's the preview.

https://marianrehak.com/66hodin/

**Comment by tholman** [comment]
Hi,

I do not see the effect on the page at all.
