### ISSUE TITLE
Whole page turns black after applying the code.

### ISSUE THREAD

**Issue by LuigiCotocea** [tholman/cursor-effects#73]
The whole page turns black but the effect on the cursor works, 
![Screenshot (1072)](https://github.com/tholman/cursor-effects/assets/46846378/d90470d2-08f6-40fa-ac9b-8851df80111d)
any fixes?

This is what i applied -  <script src="https://unpkg.com/cursor-effects@latest/dist/browser.js"></script>
        <script type="module">
              
            window.addEventListener("load", (event) => { new cursoreffects.rainbowCursor(); });
        </script>

**Comment by tholman** [comment]
I suspect you may be applying a background color to all canvas elements in your css somewhere. You should be able to inspect the page and see where.
