### ISSUE TITLE
Cursor goes behind a modal

### ISSUE THREAD

**Issue by Bamuel** [tholman/cursor-effects#77]
Using Bootstrap and created a modal,
When having a cursor effect active it works, but its behind the modal.
I believe its just a z-index to make the cursor to have a higher priority
![image](https://github.com/user-attachments/assets/4045024a-c9fa-4426-b310-ed3cbb6fb3e3)
As you can see the fairy dust is behind the modal.

**Comment by tholman** [comment]
You'll need to manage the z indexes manually
