### ISSUE TITLE
Incorrect "baseImageSrc" type for trailing cursor options

### ISSUE THREAD

**Issue by incandesc3nce** [tholman/cursor-effects#80]
I've ran into an issue in TypeScript where I couldn't use image URL as `baseImageSrc` property in trailing cursor due to it being typed as number. AFAIK Base64 is also a string and includes characters, and that would cause a conflict on build times in TypeScript.

I'm willing to contribute and open a pull request fixing this issue if that's okay.

**Comment by tholman** [comment]
Ya, very willing to merge in change, especially if its just in the types.

**Comment by incandesc3nce** [comment]
Resolved by PR #81.
