### ISSUE TITLE
Emoji not displaying correctly with text flag

### ISSUE THREAD

**Issue by Bry10022** [tholman/cursor-effects#84]
When there are emoji or other non-BMP characters in the content of text flags, they don't render correctly and are replaced with �� instead. I wonder if it'd be possible to make the code recognize such characters outside the Basic Multilingual Plane and not split them into two separate characters, which the letter gets rendered as � when they are by themselves since they are surrogate characters? (The text I used in the example was "393939💸"). 

![textflagemj](https://github.com/user-attachments/assets/345c7710-8989-4cb3-a166-0310a43577da)

**Comment by tholman** [comment]
https://github.com/tholman/cursor-effects/commit/c32d56bb5432d13dbea199c42e2f0552b5bfcdb0

This should fix it, looked good to me on some tests. published to latest npm if you're using it that way :)
